// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// BPFMapSizes BPF map sizes
// swagger:model BPFMapSizes
type BPFMapSizes struct {

	// Size of the non-TCP connection tracking map
	CtAnyMapSize int64 `json:"ct-any-map-size,omitempty"`

	// Size of the TCP connection tracking map
	CtTCPMapSize int64 `json:"ct-tcp-map-size,omitempty"`

	// Ratio of total system memory to use for dynamic sizing of BPF maps
	DynamicSizeRatio float64 `json:"dynamic-size-ratio,omitempty"`

	// Size of the NAT map
	NatMapSize int64 `json:"nat-map-size,omitempty"`

	// Size of the neighbor table map
	NeighMapSize int64 `json:"neigh-map-size,omitempty"`

	// Size of the sock reverse NAT map
	SockRevMapSize int64 `json:"sock-rev-map-size,omitempty"`
}

// Validate validates this b p f map sizes
func (m *BPFMapSizes) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BPFMapSizes) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BPFMapSizes) UnmarshalBinary(b []byte) error {
	var res BPFMapSizes
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
